services:
  openpod:
    build:
      context: .
      network: host
    image: oh-my-openpod:0.4.0.dev5
    container_name: openpod
    stdin_open: true
    tty: true
    working_dir: /workspace
    volumes:
      - ${PROJECT_DIR:-.}:/workspace
    env_file:
      - path: .env
        required: false
    network_mode: host
    restart: "no"
